### PR TITLE
test echo range for EK80 reduced sample rate

### LINKED ISSUE #969: Add test for `echo_range` for EK80 reduced sampling rate data
This is a leftover from #968 where the `echo_range` output dimension should also be checked for EK80 reduced sampling rate data.

This may be related to #702.

### PR DESCRIPTION
**Pull request by MohamedNasser8**
Fixes #969 
I don't know if the mean by reduced sampling rate is the reduced file size, if it is, The **fifth** test case do the same thing as me.
Or I should resample the data?

### CODE REVIEW

**Comment by leewujung** [comment]
@MohamedNasser8 : My bad, I did not put in enough info the original description in #969.

Here the reduced sampling rate refers to a specific setup the EK80 instrument allows. That setup would make the discretization along the `range_sample` axis coarser in the `EchoData` object (from the `open_raw` function), which affects the `echo_range` values in the output of `compute_Sv`. The intention of #969 is to check the calculation against the expected values from another program. I got some sample data from a colleague from #702, and will put that somewhere for you to download, and the expected values it should be tested against.

**Comment by MohamedNasser8** [comment]
@leewujung Thanks for your illustration, I'm waiting for the data to test it.

**Comment by MohamedNasser8** [comment]
Hello @leewujung, I just wanted to remind you about the data I can test with.

**Comment by ctuguinay** [comment]
I'm going to close this. I think this should probably be tested when we get in-lab EK80 systems in conjunction with the many other  possible configurations @leewujung

**Comment by leewujung** [comment]
yeah but probably should keep this open as a reminder?

**Comment by ctuguinay** [comment]
Ah yeah I see

**Comment by leewujung** [comment]
Looking at this again I agree with you @ctuguinay that we should just close this. We have #969 as a reminder.

**Pull request closed without merging**
