### PR TITLE
Add support for AZFP 130kHz

### PR DESCRIPTION
**Pull request by ctuguinay**
As indicated by Steve Pearce from ASL, I used the same transmit frequency, pulse length, Sv compensation mapping that 125kHz has for 130kHz.

This addresses #1304, #1305.

### CODE REVIEW

**Comment by ctuguinay** [comment]
Oh wait, perhaps I don't need to check all 3 locations for that frequency haha. Let me change that in the morning.

**Comment by ctuguinay** [comment]
@leewujung This should be ready for review

**Review by leewujung — DISMISSED** [review]
Thanks @ctuguinay! This looks great.

The only comment I have is to add also a dict item for 120000.0 since ASL said that the same 150us and 250us mapping could be used for 120, 125, and 130 kHz transducers. Feel free to merge once that is added.

**Review by leewujung — APPROVED** [review]

**Comment by leewujung** [comment]
Oh wow, ok. Sorry I had missed this - will merge now!

**Pull request merged**
