### PR TITLE
Re-attach `frequency_nominal` to MVBS dataset

### LINKED ISSUE #693: Add frequency_nominal to compute_MVBS
Now that `frequency` is no longer a dimension & coordinate variable, MVBS is generated w/o information about the frequency values. In `compute_MVBS`, we need to pass on `frequency_nominal` from `Sv`.

### PR DESCRIPTION
**Pull request by leewujung**
This PR fixes #693.

### CODE REVIEW

**Comment by leewujung** [comment]
@emiliom : note that I started from my PR #687, because that one squeezes out the `beam` dimension for all `ds_Sv` used in the MVBS computation. That is a small PR and of the same "sort" as this one. Do you mind reviewing that and merge? Thanks!

**Comment by emiliom** [comment]
Quick question: it looks like this PR also includes the beam-squeezing changes that are in PR #687. Correct? If so, I assume it'd be best (cleaner, less confusing) to review and merge that PR first.

**Comment by leewujung** [comment]
Yep, I guess my added comment didn't get to your inbox fast enough!
Could you please review that one? (I promise it is small!)
Thanks!

**Comment by emiliom** [comment]
Looks good, tests are passing, and my own local, manual tests confirm the results. Thanks! Merging.

**Pull request merged**
