### PR TITLE
Securing and improving CI

### PR DESCRIPTION
**Pull request by lsetiawan**
This PR improves the CI by using the test data contained within the http image. This also secures the CI since now we are not using `pull_request_target` and it doesn't need the google secrets stuff anymore.

### CODE REVIEW

**Comment by emiliom** [comment]
This looks helpful. Will it require changes to the steps needed for running the tests locally, as opposed to via the GH Actions CI? For reference: https://doc-test-echopype.readthedocs.io/en/latest/contributing.html#running-the-tests
(but note that I still need to go back to our earlier discussions to finalize those instructions)

**Comment by emiliom** [comment]
> This PR improves the CI by using the test data contained within the http image.

So, will the test data be in the `cormorack/http:2021.04.06` image on docker hub?

**Comment by lsetiawan** [comment]
> So, will the test data be in the cormorack/http:2021.04.06 image on docker hub?

Yepp. :smile:. I was thinking we can update that if the test data changes for now.

**Comment by lsetiawan** [comment]
> Will it require changes to the steps needed for running the tests locally

Yea it'll need to change a little bit, but users won't need any credential files.

**Comment by emiliom** [comment]
Are you waiting on one of us to merge? As far as I can tell, this looks fine. I don't feel a need to test it locally myself.

I have mixed feelings about moving the test data to the http docker image. I totally agree that it'll make the CI substantially simpler, a bit faster (though that's probably a small impact), and probably more secure. But it introduces a hidden complexity and bottleneck to future test data updates. Granted, changes to the data probably won't happen frequently. But unless you introduce a CI/process to (semi)automatically update the docker image when test data are changed on Google Drive, we'll have to ping you to update the docker image yourself.

**Comment by lsetiawan** [comment]
@emiliom This is not ready for merging yet. The test is still failing. Idk why fsspec is erroring out ...

**Comment by lsetiawan** [comment]
> But unless you introduce a CI/process to (semi)automatically update the docker image when test data are changed on Google Drive, we'll have to ping you to update the docker image yourself.

I was thinking of doing daily updates for now.

**Comment by lsetiawan** [comment]
The actual CI workflow is now running as expected. There are actual issues in the tests.

**Comment by leewujung** [comment]
> There are actual issues in the tests.

I thought the tests in test_convert.py were all passing before?  (i am in between meetings, so may be slow to respond)

**Comment by lsetiawan** [comment]
> I thought the tests in test_convert.py were all passing before?

It was but I think it started failing after some of your changes. I will check and fix it.

**Comment by leewujung** [comment]
🤯 ok let me know what I can help. I briefly looked at the log but it didn't immediately jump out on me what failed.

**Comment by lsetiawan** [comment]
Will do! :smile:

**Pull request merged**
