### PR TITLE
Add dataset and variable-level provenance to new mask and add_splitbeam_angle functions

### PR DESCRIPTION
**Pull request by emiliom**
**WARNING:** the PR apparently can't be automatically merged to `dev`! But it can be merged to `old_dev`. I haven't investigated this. I'll keep this PR as a draft until that's resolved. @leewujung you're the expert on the `dev` vs `old_dev` issue.

Add provenance attributes to the outputs of the mask functions `apply_mask` and `frequency_differencing`. Specifically:
- `mask_type` and `history` variable attributes added to the mask dataarray returned by `frequency_differencing`. `history` captures the actual operation performed, based on the arguments passed to the function.
- dataset-level standard provenance attributes (from `prov.echopype_prov_attrs`) and Sv `history` variable attribute. The latter is concatenated with the mask `history` string. In addition to these new attributes, the `long_name` and `actual_range` attributes are updated. Note that this initial implementation can only handle mask attribute extraction for a single mask dataarray; if more than one mask is passed, only the attributes from the first one will be used. Handling of attributes from >1 mask will be added in a future release.

Add variable-level `history` attributed to the variables (datarrays) added by the new function `add_splitbeam_angle` and the existing function `add_depth`, both of which are `Sv` consolidate functions.

A few small fixes were also applied.

No tests were added. Tests for attribute content is a larger issue that will be addressed in a future release. See #831 and #769

### CODE REVIEW

**Comment by emiliom** [comment]
I could click on `Resolve conflicts` above and resolve the conflicts (I've looked at them). But I'm not sure if there's a larger issue of merging against the new, "squashed" dev vs the old dev :exploding_head:

**Comment by leewujung** [comment]
@emiliom : I tested the resolve conflict and merge operations in my fork and everything worked out, so I resolved the conflicts again here (I think those are _after_ I updated the new `dev` branch) and will go ahead to **squash** and merge. Thanks for the provenance addition!

**Comment by leewujung** [comment]
@emiliom : on the merge to `dev` you can see that there's a small assertion error that trips the test due to the added history and unit attributes. Could you please send another PR to patch these up? We'll have to address the larger issue of testing for attributes soon -- it has become cumbersome in recent developments to keep on having to look after this.

**Comment by emiliom** [comment]
> on the merge to dev you can see that there's a small assertion error that trips the test due to the added history and unit attributes. Could you please send another PR to patch these up? 

Great, thanks! Could you point me to the assertion error? I can see that tests involving version conversion could fail, but the CI tests didn't fail and I also didn't see any errors when I ran the test suite locally just before submitting the PR.

> We'll have to address the larger issue of testing for attributes soon -- it has become cumbersome in recent developments to keep on having to look after this.

Yup

**Comment by leewujung** [comment]
https://github.com/OSOceanAcoustics/echopype/actions/runs/3783076757/jobs/6431330051#step:11:1368

Not sure why this is not run at PR level.

**Pull request merged**
