### PR TITLE
Make matplotlib an optional dependency

### PR DESCRIPTION
**Pull request by emiliom**
Addresses #526 (and is a follow up to the failed PR #527)

### CODE REVIEW

**Comment by emiliom** [comment]
I'd neglected to remove `matplotlib` from `requirements.txt`, so I did that now in a new commit

**Comment by emiliom** [comment]
Hmm, RTD build failed and it IS related to matplotlib and the `visualize` subpackage:
```
[autosummary] generating autosummary for: api.rst, contributing.rst, convert.rst, data-format.rst, examples.rst, index.rst, installation.rst, open-converted.rst, process.rst, resources.rst, whats-new.rst, why.rst
Failed to import echopype.
Possible hints:
* ModuleNotFoundError: No module named 'matplotlib'
* KeyError: 'echopype'

...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/envs/529/lib/python3.7/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/envs/529/lib/python3.7/site-packages/sphinx_automodapi/automodsumm.py", line 257, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/envs/529/lib/python3.7/site-packages/sphinx_automodapi/automodsumm.py", line 329, in automodsumm_to_autosummary_lines
    filestr = automodapi.automodapi_replace(fr.read(), app, True, docname, False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/envs/529/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 303, in automodapi_replace
    modnm, toskip, includes, onlylocals=onlylocals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/envs/529/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 415, in _mod_info
    for localnm, fqnm, obj in zip(*find_mod_objs(modname, onlylocals=onlylocals)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/envs/529/lib/python3.7/site-packages/sphinx_automodapi/utils.py", line 81, in find_mod_objs
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/checkouts/529/echopype/__init__.py", line 5, in <module>
    from . import calibrate, preprocess, visualize
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/checkouts/529/echopype/visualize/__init__.py", line 1, in <module>
    from .api import create_echogram
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/checkouts/529/echopype/visualize/api.py", line 6, in <module>
    from .plot import _plot_echogram, FacetGrid, QuadMesh, T
  File "/home/docs/checkouts/readthedocs.org/user_builds/echopype/checkouts/529/echopype/visualize/plot.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by emiliom** [comment]
Maybe the solution to this RTD failure is to add `matplotlib` to [docs/requirements.txt](https://github.com/OSOceanAcoustics/echopype/blob/main/docs/requirements.txt)?

**Comment by lsetiawan** [comment]
Just added the fix. We just gotta make sure to install the extra requirements 😄

**Comment by lsetiawan** [comment]
Is the name "plot" makes sense for this extra requirement or should it be the same as the module "visualize"? 🤔

**Comment by emiliom** [comment]
Do you mean in both `setup.py` and `.readthedocs.yml`? Does it have any concrete impacts on anything, or it more about consistent labeling and minimizing confusion?

**Comment by emiliom** [comment]
What's the reason for having matplotlib in `.readthedocs.yml` rather than in `docs/requirements.txt`? I ask b/c the latter is easier to incorporate into a local conda env creation statement (for local development & testing). 

And actually, this leads me to a broader realization: the sphinx plugins and other sphinx-related dependencies are currently listed in **both** [docs/requirements.txt](https://github.com/OSOceanAcoustics/echopype/blob/main/docs/requirements.txt) and [requirements-dev.txt](https://github.com/OSOceanAcoustics/echopype/blob/main/requirements-dev.txt). Wouldn't it make more sense to remove them from `requirements-dev.txt`? Then, if you want to do local sphinx development & testing, you'll have to include `docs/requirements.txt` in the conda env.

**Comment by lsetiawan** [comment]
> Do you mean in both setup.py and .readthedocs.yml? Does it have any concrete impacts on anything, or is it more about consistent labeling and minimizing confusion?

Just consistencies.

> What's the reason for having matplotlib in .readthedocs.yml rather than in docs/requirements.txt? I ask b/c the latter is easier to incorporate into a local conda env creation statement (for local development & testing).

In terms of dependencies in the future, it's better to have all of those docs requirements in the setup.cfg. I think for now we should just merge this and I will provide more overhaul in listing out dependencies in a separate PR.

**Comment by emiliom** [comment]
> In terms of dependencies in the future, it's better to have all of those docs requirements in the `setup.cfg`. I think for now we should just merge this and I will provide more overhaul in listing out dependencies in a separate PR.

I'm happy to merge this PR. I'll do that in a bit.

I'd like to hear about what benefits setup.cfg brings us before you invest time in it, though. But let's discuss elsewhere

**Pull request merged**
