### PR TITLE
Centralize/generalize declaration of convention attributes

### PR DESCRIPTION
**Pull request by emiliom**
This is a demonstration step for centralizing where coordinate and variable attributes are declared. Moving in this direction will make it easier and more robust to maintain adherence to the convention.

Not ready for merging. Though it completes all tests, this PR is intended as a demonstration for discussion.

Sorry for the clutter, but it also contains changes from PR #492, which is not merged yet; those are all in `echopype/echodata/echodata.py` alone.

Partially addresses #373 (adds `range_bin` attributes, but not a description in the docs).

### CODE REVIEW

**Comment by emiliom** [comment]
TODO: Change from using the attribute definitions in `attrs.py` to reading it dynamically from a yaml file.

**Comment by emiliom** [comment]
@leewujung & @lsetiawan : a test failed with this PR. When I first created the PR 19 days ago, all tests were successful. [The error](https://github.com/OSOceanAcoustics/echopype/runs/4403128436?check_suite_focus=true#step:15:180) occurs with `test_convert_ek80_cw_bb_in_single_file`, and involves a failure to find a raw file:
```
E           FileNotFoundError: There is no file named Summer2018--D20180905-T033113.raw
```
I don't see how that could be caused by the changes in this PR, so my guess is that it has to do with something else altogether. Has there been a change in the availability of EK80 test files in the last ~24 hours (eg, related to #498)? I'm hoping this is a transient hiccup. Could either of you take a quick look to diagnose if it looks like it's an external problem that will be addressed elsewhere?

If the problem persists into tomorrow and it's hard to diagnose, let's skip this PR for 0.5.5.

**Comment by leewujung** [comment]
Oops, that's my fault, as part of the work for #498. It's a tiny `_` vs `-` that took me half an hour to debug out... and I forgot to rename the file in the CI_test_data folder. It should run now.

**Comment by leewujung** [comment]
Also, @emiliom there seems to be some unused import thing found by the pre-commit.ci bot. Could you check on those?

**Comment by emiliom** [comment]
> Oops, that's my fault, as part of the work for #498. It's a tiny _ vs - that took me half an hour to debug out... and I forgot to rename the file in the CI_test_data folder. It should run now.

Thanks! Good for me, bad for you

> Also, @emiliom there seems to be some unused import thing found by the pre-commit.ci bot. Could you check on those?

Nice catch. I'll admit that I had ignored the pre-commit failures altogether. I've fixed it.

**Comment by leewujung** [comment]
Ok this is ready to merge now. Thanks @emiliom!

**Pull request merged**
