### PR TITLE
Unify `echo_range` order of dimensions across sonar models

### PR DESCRIPTION
**Pull request by leewujung**
This PR ensures that the order of dimensions of `echo_range` as part of the calibration outputs are the same across all sonar models, by doing the following:
- reorder order of dimension in AZFP `echo_range` output (previously it was done in an ad-hoc way at the end of `compute_Sv/TS` (this addresses #752)
- add tests to ensure all `echo_range` dimensions are of the following sequence `("channel", "ping_time", "range_sample")`

Note: this is built on top of #955 so only the last batch of commits are for this PR. #955 should be merged first before this can be merged.

### CODE REVIEW

**Comment by leewujung** [comment]
@emiliom : Since the changes here are so compounded those in #955, I made a mock in my branch (https://github.com/leewujung/echopype/pull/30) so that you could see that the actual changes in this PR only involves 3 files, including a new test file. This should make reviewing this easier. :)

**Comment by emiliom** [comment]
Thank you!!! That makes a huge difference :smile:

**Comment by emiliom** [comment]
`test_range_intergration.py` is mispelled. It should be `test_range_integration.py`

**Comment by emiliom** [comment]
See my broader comment in https://github.com/OSOceanAcoustics/echopype/issues/752#issuecomment-1464251113. Assuming we stick with having the transpose step in `range.py`, the change in this PR seem to do the trick. However, I'd make one suggestion. Rather than hard-wiring the same dimension order twice in `range.py`, for EK and AZFP, let's define a global variable that's then reused. eg:
```python
DIMENSION_ORDER = ["channel", "ping_time", "range_sample"]

# ...

range_meter = range_meter.transpose(*DIMENSION_ORDER)
```

I'll go over and run the test in a bit.

**Comment by emiliom** [comment]
The tests pass, but note the divide by zero warnings on ek80_bb_complex and ek80_cw_power:

```
echopype/tests/calibrate/test_range_intergration.py::test_range_dimensions[ek80_bb_complex]
  /home/mayorga/miniconda3/envs/echopype_dev/lib/python3.9/site-packages/xarray/core/computation.py:727: RuntimeWarning: divide by zero encountered in log10
    result_data = func(*input_data)

echopype/tests/calibrate/test_range_intergration.py::test_range_dimensions[ek80_cw_power]
  /home/mayorga/miniconda3/envs/echopype_dev/lib/python3.9/site-packages/xarray/core/computation.py:727: RuntimeWarning: invalid value encountered in log10
    result_data = func(*input_data)
```

**Review by emiliom — COMMENTED** [review]
Given your comment in #752, this PR looks good. But take a look at my suggestion in https://github.com/OSOceanAcoustics/echopype/pull/968#issuecomment-1464256709
If you agree, it's easy to implement.

**Comment by leewujung** [comment]
> note the divide by zero warnings on ek80_bb_complex and ek80_cw_power

Great, thanks for noting this. This is on the list of issues to address for v0.7.0 (#737) so I'll link your comment there.

**Comment by emiliom** [comment]
I've pushed these changes:
- Use of global `DIMENSION_ORDER` variable (see above)
- Fixed spelling error in `test_range_intergration.py` file name

**Pull request merged**
