### PR TITLE
Set range entries with no backscatter data to `NaN` in output of `echodata.compute_range()`

### PR DESCRIPTION
**Pull request by leewujung**
This PR sets entries in the `range` data variable in the output dataset from `compute_Sv` that does not have corresponding backscatter entries (also set to NaN) to NaN. Some backscatter entries are NaN due to changes in echosounder settings, such as data collection range, transmit signal duration, etc. 

The change addresses the potential confusion #483.

## Tasks
- [x] set `range` entries with no backscatter data to `NaN` in `echodata.compute_range()`
- [x] update tests to test for NaN entries

### CODE REVIEW

**Comment by leewujung** [comment]
@lsetiawan : In our current testing setup, since this PR only "touches" `echodata.py`, only tests under `tests/echodata` were run. In practice, the method (`compute_range()`) being updated here is used in the calibration functions, so tests under `tests/calibrate` should also be run. Right now the entire set of tests are only run when merged to `main` so the calibration tests will only be run then.

What's the best practice here? I think we were tripped a few times by this (i.e., additional fixes needed when merging `dev` to `main` due to the adaptive test not catching bugs that are downstream from the code being modified in the PR).

Can we set up something that pulls out the downstream pieces that uses the changed functions  and run the corresponding tests? If we do this, at what stage this should be run -- when it is merged to `dev`, or as a label such as what is done with putting on the label `Needs Complete Testing`?

**Comment by leewujung** [comment]
@lsetiawan : I merged your #523 and used the fixture structure for the test here. Also added an EK60 file (`test_data/ek60/Winter2017-D20170115-T150122.raw`) that contains NaN entries in addition to the EK80 file (`test_data/ek80/D20170912-T234910.raw`) that we already have there.

**Comment by lsetiawan** [comment]
> What's the best practice here? I think we were tripped a few times by this (i.e., additional fixes needed when merging dev to main due to the adaptive test not catching bugs that are downstream from the code being modified in the PR).

The CI is now setup to run all tests when merged to dev as shown here: https://github.com/OSOceanAcoustics/echopype/blob/0f699cce311c5b86a897f167496ab852f7d2fbb1/.github/workflows/ci.yaml#L91-L94

So as a first step, as long as the isolated module test works you can merge to dev for a full test. Or you can always just use the `Needs complete testing` label with the PR if you know that particular function touches many different things. In practice, most software CI actually runs everything anyways to make sure your changes doesn't break anything, we just decided to make this custom, brittle, intelligence 😜

**Comment by emiliom** [comment]
> Or you can always just use the `Needs complete testing` label with the PR if you know that particular function touches many different things.

And whenever you have a need for that mechanism but don't remember how to use it, go to the docs: https://echopype.readthedocs.io/en/stable/contributing.html#continuous-integration-github-actions

**Comment by leewujung** [comment]
Hmm, we should revisit this soon, in terms of how/what we want the tests to be set up. The past few times tests failed when merging to `main` I think was after the supposedly complete test when merging to `dev`, and we opted for fixing the bugs for obvious reasons then.

In theory we can get out of the current brittle setup once most big test data files are updated to a smaller size. I updated 2 major ones, but ran out of time to do the last couple files before I had to return a hardware dongle needed to generate data we test against -- the next time I can do this is likely late March - April. 

BUT regardless, it is unlikely we'll be able to reduce all files to be KB size like the new EK80 test files I collected, since we don't have access to many instrument variations that were used to collect the diverse test files.

**Review by lsetiawan — APPROVED** [review]
LGTM! Thanks for this awesome work. I need to think about the whole testing scheme and see how we can improve it 😄 Would you mind, pasting all of the thoughts from here to an issue so we can discuss there? Thanks @leewujung

**Comment by lsetiawan** [comment]
> The past few times tests failed when merging to main I think was after the supposedly complete test when merging to dev, and we opted for fixing the bugs for obvious reasons then.

Just checked this. The tests failed the past few times on main due to the publish to PyPi action issues, which is more of a packaging issue rather than code. I think I need to figure out how to activate that within the dev branch also so it imitates main. In terms of full CI testing PR #411 fixed the missing testing since the test for all testing are actually run directly with pytest rather than the small script I created.

**Comment by leewujung** [comment]
> Just checked this. The tests failed the past few times on main due to the publish to PyPi action issues, which is more of a packaging issue rather than code. 

Thanks for checking @lsetiawan , I must have confused that and the other earlier ones! Great that there was no unexpected behavior!

And yes I'll paste the thoughts we've had here to a new issue. :)

**Pull request merged**
