### PR TITLE
replace matpplotlib with matplotlib-base in requirements

### PR DESCRIPTION
**Pull request by emiliom**
Addresses #526

### CODE REVIEW

**Comment by emiliom** [comment]
Hmm. It looks like `matplotlib-base` is only available on conda, not on pypi (pip). But much/all of the test infrastructure creates an environment using pip, so all tests (and readthedocs) fail at that point.

This issue & PR are not important. It just seemed like a very easy, nice improvement to the packaging. But I can withdraw the PR unless someone has an easy solution. It's not worth spending much time on this, IMHO.

**Comment by emiliom** [comment]
We've decided to go in a different direction, to make matplotlib an optional dependency. We'll add matplotlib to https://github.com/OSOceanAcoustics/echopype/blob/main/setup.py#L16, like this:
```python
EXTRA_REQUIRES = {"dev": dev_reqs, "plot": ["cmocean", "matplotlib"]}
```

@lsetiawan is that correct?

**Comment by lsetiawan** [comment]
Yepp that is correct 👍🏽

**Comment by emiliom** [comment]
Thanks. I'll close this PR and create a new one by tomorrow.

**Pull request closed without merging**
