### PR TITLE
Restructure data format section in docs

### PR DESCRIPTION
**Pull request by leewujung**
This is to address #597.

### CODE REVIEW

**Comment by leewujung** [comment]
Notes from meeting:
- HTML repr printouts for each sonar model in a separate page from the Data format page
- another new subsection: Creation of adding of the channel dimension
- HTML: xarray repr for processed data example

**Comment by leewujung** [comment]
Remember to add an attention item that the Platform messages were "filtered" (only 3 NMEA sentences allowed) in v0.5.x files but will be "raw" (include all NMEA sentences in the raw data files) in v0.6.0. So, v0.5.x files will potentially have some sentences missing. Related to #580 https://github.com/OSOceanAcoustics/echopype/issues/656#issuecomment-1122624196 #673

**Comment by leewujung** [comment]
Notes for our later selves: The v0.5.x HTML printout is from https://github.com/OSOceanAcoustics/echopype/pull/503

**Comment by leewujung** [comment]
@emiliom : I've done some restructuring of sections and add some new materials. The main thing is to consolidate all data format-related information under a "Data format" section, with 3 pages "Raw converted data", "Processed data", and "v0.5.x to v0.6.0 changes".

Let me know what you think. I will switch my attention to the other issues related to the code itself before coming back to this. Feel free to directly push to my branch for changes. Thanks!

**Comment by b-reyes** [comment]
Note: once this documentation is ready to go, @leewujung and myself suggest that we merge the docs to stable first. That way we can link to [docs/source/data-format-5to6.ipynb](https://github.com/OSOceanAcoustics/echopype/pull/635/files#diff-b71154ef9cb4b8702598bfab98d9b4ebe929049dd9ff7c07059ba39cc32294e1) in the conversion routine. In PR #685 I have put `# TODO: put in an appropriate link to the v5 to v6 conversion outline` where I think this link should be put.

**Comment by emiliom** [comment]
A general comment, not specifically about the changes in the PR: I think we should remove all the old "attention" blocks that refer to what was new in 0.5.0. I'll plan to remove them when I push commits to this PR.

**Comment by emiliom** [comment]
@leewujung do you intend to include computational elements/cells in the `v0.5.x to v0.6.0 changes` page? It's currently a notebook, but I think it'd be easier to edit and review as a markdown page. I don't see anything there that would require a notebook. BTW, the summary-of-changes table is awesome!

**Comment by leewujung** [comment]
@emiliom : there's not really a reason for it to be a notebook, but it was more convenient (at that moment) and (looking back) maybe extendable if we find the need?

**Comment by emiliom** [comment]
Thanks. Definitely extendible. But I figured that page is not likely something we'd invest effort into adding computational elements. Anyway, I'll decide if it's worth my time to look into a markdown + HTML version right now; it probably isn't.

**Comment by leewujung** [comment]
I think if you have the time, changing the embedded HTML file so that the fonts are identical to all the rest of the docs might be a better investment. Isn't one of the points of having this flexibility in jupyterbook such that we don't need to worry about what things are written in exactly, unless there's something that cannot be achieved in some specific format?

**Comment by emiliom** [comment]
> I think if you have the time, changing the embedded HTML file so that the fonts are identical to all the rest of the docs might be a better investment. 

Given my rusty HTML/CSS chops, that's probably beyond what I should try to do right now :nerd_face:

> Isn't one of the points of having this flexibility in jupyterbook such that we don't need to worry about what things are written in exactly, unless there's something that cannot be achieved in some specific format?

Yeah. My reasoning for considering markdown was mainly for the ease of review and commenting compared to notebooks. Not a powerful reason, for sure.

**Comment by emiliom** [comment]
The text in https://echopype--635.org.readthedocs.build/en/635/data-format-raw.html#organization-of-multi-frequency-data comes from the echopype preprint. I think we'll need to update some of the descriptions of what the convention is actually doing, specially with respect to channels and frequencies vis a vis groups. But let's do it after 0.6.0.

**Comment by emiliom** [comment]
@leewujung I've push the last batch of commits to the PR I created on top of this PR (https://github.com/leewujung/echopype/pull/4). Edits for the "Raw converted data" and "Processed data" were small. They were more substantial for "v0.5.x to v0.6.0 changes", but they were mainly additions. You did a great job with these pages, thank you!!

Please go over https://github.com/leewujung/echopype/pull/4 and modify or merge (into your PR) as you see fit. Then you can merge this PR. I'll go ahead and approve my review.

**Review by emiliom — APPROVED** [review]

**Comment by leewujung** [comment]
I think we are in good shape! Thanks @emiliom for the careful additions! I'll merge now.

**Pull request merged**
