### PR TITLE
Return dict and standardize prov.source_files_vars usage

### PR DESCRIPTION
**Pull request by emiliom**
Return a dict rather than list of variables .

This PR addresses the remaining task in #677.

Some tests are failing right now, but I suspect many, if not all these failures are not due to the changes in this PR. I tested the changes manually on several data files. I'll set the PR to draft and investigate further.

### CODE REVIEW

**Comment by leewujung** [comment]
@emiliom I think the failed tests are the same ones that failed unexpectedly after #837. I will investigate that today.

**Comment by emiliom** [comment]
> @emiliom I think the failed tests are the same ones that failed unexpectedly after https://github.com/OSOceanAcoustics/echopype/pull/837. I will investigate that today.

Thanks. I just ran the test suite again twice, without my changes, on a freshly pulled `dev` and on a version of `dev` from a few days ago. There were lots of failures in both cases. So, I'm guessing most, if not all of the test failures I'm seeing are not related to my changes. I'll set this aside until we know more about the tests.

**Comment by leewujung** [comment]
@emiliom : I merged the changes from #856 and all tests passed now. The code looks good to me! Feel free to merge.

**Comment by leewujung** [comment]
I'll merge this now for pre-release tests.

**Pull request merged**
