### PR TITLE
Add AD2CP parsing, remove redundant MODELS from convert

### PR DESCRIPTION
**Pull request by imranmaj**

### CODE REVIEW

**Comment by lsetiawan** [comment]
Lots of type hints! Just wanted to say these are great @imranmaj! :100:

**Comment by leewujung** [comment]
@imranmaj : do you want us to merge this or do you want to try to add back the commit history (those in #238) in another PR and we merge that one?

**Comment by imranmaj** [comment]
> Lots of type hints! Just wanted to say these are great @imranmaj! 💯

Thank you!

**Comment by imranmaj** [comment]
> @imranmaj : do you want us to merge this or do you want to try to add back the commit history (those in #238) in another PR and we merge that one?

I think I fixed the commit history, I'll submit a new PR

**Comment by imranmaj** [comment]
Closed in favor of #326

**Pull request closed without merging**
