### PR TITLE
Generalize assignment of beam coordinate var attributes

### PR DESCRIPTION
**Pull request by emiliom**
Unified where the attributes for the core beam coordinate variables (`frequency`, `ping_time`, `range_bin`) are set. I've created a new `DEFAULT_BEAM_COORD_ATTRS` dict in `set_groups_base.py` that declares these common attributes and their values, then import that variable in the various set_groups_x.py modules. This PR implements that change for ek60, ek80, azfp.This abstraction/centralization will reduce the potential for variability across sensors and make it a tiny, tiny bit easier to roll out support for new sensors in a consistent fashion.

Also added a `long_name` attribute to `range_bin`, partly addressing #373

### CODE REVIEW

**Comment by leewujung** [comment]
Thanks @emiliom, this looks great! 

One thing I thought of when going through this is that `DEFAULT_BEAM_COORD_ATTRS` should probably live somewhere else, something like `core.py` but for convention side of things. Perhaps that's something to be resolved in a more top-down form, related to the pydantic work. For now it seems fine for that to live under `set_group_base.py`.

On an _unrelated_ note, I noticed that `DEFAULT_CHUNK_SIZE` is only used for encoding EK60 data. Properly chunking is arguably going to be more important for EK80. I'll submit an issue about that so that we don't forget about that when we get to working on performance-related issues..

**Review by leewujung — APPROVED** [review]

**Comment by emiliom** [comment]
> On an unrelated note, I noticed that DEFAULT_CHUNK_SIZE is only used for encoding EK60 data. Properly chunking is arguably going to be more important for EK80. I'll submit an issue about that so that we don't forget about that when we get to working on performance-related issues..

Continuing the unrelated note, I think I noticed that DEFAULT_CHUNK_SIZE is actually declared in two different modules, the same way, But yeah, that's for another issue

**Comment by emiliom** [comment]
> One thing I thought of when going through this is that `DEFAULT_BEAM_COORD_ATTRS` should probably live somewhere else, something like `core.py` but for convention side of things. Perhaps that's something to be resolved in a more top-down form, related to the pydantic work. For now it seems fine for that to live under `set_group_base.py`.

Let's revisit that thought for sure, once we're creating the convention-compliance architecture for 0.6.0

**Comment by emiliom** [comment]
Thanks for the review. I'll self merge now

**Pull request merged**
