### PR TITLE
Development roadmap in docs

### PR DESCRIPTION
**Pull request by emiliom**
Builds on PR #636. Addresses #602.

- Provides draft but "clean" Development roadmap page
- Moves roadmap page position in the left sidebar to "Help & reference", between "What’s new" and "Contributing to echopype"

### CODE REVIEW

**Comment by emiliom** [comment]
A couple of things to note:

- This PR is against `dev`. We had talked about updating `stable` before the release is out. Depending on the timing of the 0.6.0 release, that may not buy us any extra public availability anymore
- The text says "in the upcoming 0.6.0 release" in a few places. We'll need to revise that language when 0.6.0 is released, or in preparation for it

**Comment by leewujung** [comment]
Thanks @emiliom !  I pushed some small changes, and think this is ready to be merged!

The only thing I'd raise here is that the location of roadmap seems a little hidden? But maybe that's just me?

**Review by leewujung — APPROVED** [review]

**Comment by emiliom** [comment]
> Thanks @emiliom ! I pushed some small changes, and think this is ready to be merged!

Great. I'll let you merge.

> The only thing I'd raise here is that the location of roadmap seems a little hidden? But maybe that's just me?

It is definitely less prominent. Personally, I think it does belong in that section aimed at developers, contributors and other interested parties; that's what xarray does. I tend to think that what's in front/top should be what users will look for to actually use the software.  But I can also see value in having it where you had it originally, in the first section. If you think it really belongs there, please go ahead and change it in `_toc.yml`, and let's go with that. We can always discuss it again down the road.

**Comment by leewujung** [comment]
I think we can tune this later. Merging now!

**Pull request merged**
