### PR TITLE
Fix echodata repr test

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR fixes the repr test to match with the updated repr for echodata.

### CODE REVIEW

**Comment by lsetiawan** [comment]
I have setup branch protection and master need 2 approvals, so if you two (@emiliom, @leewujung) can approve that would be awesome :smile: Thanks! Let me know what you think of this branch protection! Is it too much to require 2 approvals?

**Comment by leewujung** [comment]
Haha, i was wondering about that, when I forced merge last night. 😛

I suspect we may need to go by 1 reviewer due to time availability issue, but happy to go with 2 if we want to make sure all changes are vetted thoroughly. Let's see what @emiliom thinks.

**Comment by emiliom** [comment]
> master need 2 approvals

So, that's 2 approvals **in addition** to your own? If so, yeah, IMHO that's too much. Anyway, I'll approve right now.

**Review by leewujung — APPROVED** [review]

**Comment by emiliom** [comment]
I was able to merge. I guess that's b/c @leewujung had already approved?

**Comment by lsetiawan** [comment]
You both have admin access hence you're able to merge, otherwise outside users would need 2 approval from any of us.

**Comment by emiliom** [comment]
Ah! I thought you meant that even admins needed 2 approvals. Aren't you an admin? So, admins can still self merge into master?

**Comment by leewujung** [comment]
@lsetiawan: I agree, I think for PR from outside users it's a good idea to have 2.

**Pull request merged**
