### PR TITLE
Release v0.6.1 [all tests ci]

### PR DESCRIPTION
**Pull request by leewujung**
This is a PR that contains all changes for v0.6.1 release.

### CODE REVIEW

**Comment by lsetiawan** [comment]
I know what's going on here. The current PR uses the older pr.yaml github action, which skips CI when there's `[skip ci]` in the commit message, which there are! So that's why the CI is not running.

**Comment by leewujung** [comment]
I see. So this has to be merged to `main` for this to run, is that true?

**Comment by lsetiawan** [comment]
Yepp exactly. I think as long as dev passes. We should be good.

**Comment by leewujung** [comment]
I'll merge this to `main` now. Everything passes locally and the failures are the usual intermittent ones. Packaging passed also.

**Pull request merged**
