### PR TITLE
Fixes `UnicodeDecodeError` for ES60 files [all tests ci]

### PR DESCRIPTION
**Pull request by praneethratna**
Addresses #1195 by changing encoding to `unicode_escape` instead of using default encoding `utf-8`.

CC @leewujung

### CODE REVIEW

**Comment by emiliom** [comment]
I'll add "[all tests ci]" to the PR title and closing-reopening the PR to force all tests to be run, to ensure there are no negative consequences with other EK/ES data. As it stands, it looks like none of the tests were actually run in the CI.

**Comment by praneethratna** [comment]
Ping @emiliom, should we add a new test case using the data file provided here - https://github.com/OSOceanAcoustics/echopype/issues/1195#issuecomment-1788674130?

**Comment by leewujung** [comment]
@praneethratna: thanks for looking in to this! I checked the example ES60 file and this happens in the `spare0` field and with `encoding="unicode_escape"` it returns `'7B\x00\x00\x90A'`. With a regular EK60 file, the same `spare0` field returns `'\x00\x00\x00\x00\x00\x00'`. I think this is fine since this field doesn't actually encode anything useful.

I am a little reluctant to add a 100MB file into the test data set. Let's ping the person who raised this issue to see if they could help provide a smaller file.

We can merge this once we decide whether we would add a smaller test data file into this (if such file exists). If not, we can add a comment that this error occurred for an ES60 file.

**Comment by emiliom** [comment]
@praneethratna I've gone ahead and uploaded the new small test file (https://github.com/OSOceanAcoustics/echopype/issues/1195#issuecomment-1805255054) to our test folder on Google Drive. I created a new top-level folder, `es60`. BTW, that really is a tiny file -- just 11KB! I haven't tried opening it.

I think you can go ahead and create a test for it. Thanks!

**Comment by leewujung** [comment]
@praneethratna: I've just verified that the 11KB file does contain the type of byte string that was not previously decoded. Please go ahead to add a test for this file under `test_convert_ek60.py`. Thank you!

**Review by leewujung — APPROVED** [review]

**Pull request merged**
