### PR TITLE
Feature/add multichannel masks

### PR DESCRIPTION
**Pull request by ruxandra-valcu**
This PR introduces multichannel mask functionality to apply_mask

- if a single-channel mask is provided as argument, it will be applied to all channels of the dataset
- if a multi-channel mask is provided as argument, its channels will be applied individually

### CODE REVIEW

**Comment by leewujung** [comment]
Hey @ruxandra-valcu : Thanks for the PR! Could you revert the new commits so that this PR only contains changes that are relevant to the multi-channel mask support? It is very difficult to figure out what was changed otherwise. From a quick look the actually changes are small, so I will be able to review quickly. Thanks!

**Comment by ruxandra-valcu** [comment]
Reverted,sorry about that!

**Comment by leewujung** [comment]
Thanks, I'll get to this very soon!

**Comment by leewujung** [comment]
I'll close this now as it is being addressed as part of #1230.

**Pull request closed without merging**
