### PR TITLE
Add summary statistics and tests

### PR DESCRIPTION
**Pull request by stuara**

### CODE REVIEW

**Comment by leewujung** [comment]
@stuara : while you are on the task of linting, could you also add docstring for each function? Thanks!

**Comment by stuara** [comment]
Added docstrings directly from [Urmy](https://academic.oup.com/icesjms/article/69/2/184/701699) and lint corrections for summary_statistics.py. A couple of things:

- I don't think a lint check happened for test_summary_statistics.py
- I still don't see the check for the actual compiling of test_summary_statistics, but this could just be because I don't quite know how to view all details in pre-commit

**Comment by lsetiawan** [comment]
Let's wait for #401 to get merged first, then I'll let you know how to make this metrics test to run. Thanks! 😄

**Comment by lsetiawan** [comment]
For pre-commit you can do the following:
1. Install `pre-commit` into your development conda environment `conda install -c conda-forge pre-commit`
2. Run `pre-commit`: `pre-commit run --all-files`.

**Comment by lsetiawan** [comment]
@stuara What IDE are you using to write code? I think your IDE, must be setup that when you do `tab` it's actually filling the spaces with tabs rather than actual spaces. Ideally, you should have your IDE setup to tabs giving out **4 spaces**. I have fixed up your code so far to remove all the tabs that causes the pre-commit to fail because it can't fix tabs. 

When you get a change could you pull down the changes I've made to your local git, and then also pull the latest `dev` branch to this branch? Thank you! Let me know if you have any questions. After you have done that then I think we can move forward to adding this module to be tested in the CI.

**Comment by stuara** [comment]
@lsetiawan Huh, that thing with the tabs is odd. I've been working in Jupyter Lab. Thanks for fixing it though!

I think I have done those two things, as well as the pre-commit as you instructed. I'm not 100% sure but it seems like everything is up to date?

**Comment by lsetiawan** [comment]
>  I'm not 100% sure but it seems like everything is up to date?
From what I can see, you branched off @leewujung branch, which she seemed to have branched off master at some point in time. Currently, your branch doesn't have the latest `dev` changes that contains the updates of the `run-test.py` script to run the testing, which then you can't really add this module to test within the CI without the new changes.

@stuara you can simply do the following:
1. `git checkout add-metrics`
2. `git pull origin dev` (**Note: Make sure the `origin` points to the main repo *OSOceanAcoustics*.**)

You can double check origin by doing `git remote -v`. You should get something like below:
Screenshot from 2021-08-12 09-40-57
The `origin` should be associated to `https://github.com/OSOceanAcoustics/echopype.git`. If not, you can always add it as a git remote destination. Just make sure to remember the name of it. 

For example, you can add it as `upstream`:
`git remote add upstream https://github.com/OSOceanAcoustics/echopype.git`. 

Then the step 2 for git pull would change to `git pull upstream dev`. Does that makes sense? Thanks!

**Comment by lsetiawan** [comment]
>  Huh, that thing with the tabs is odd. I've been working in Jupyter Lab. Thanks for fixing it though!

I'm not sure what happened then.. But you could always, make sure by going to settings.

Screenshot from 2021-08-12 09-50-25

**Comment by stuara** [comment]
@lsetiawan Okay, I think during our meeting Wu-Jung and I resolved the upstream issue. Apparently, I just hadn't pushed from local to my branch on github

**Comment by leewujung** [comment]
@lsetiawan @stuara : so no tests were run for these changes since the CI is not pointed to it, but seems like we're now in place to add that in...

**Comment by emiliom** [comment]
> The `origin` should be associated to https://github.com/OSOceanAcoustics/echopype.git. If not, you can always add it as a git remote destination. Just make sure to remember the name of it.

I may be nitpicking, but for the sake of consistency and minimizing confusion (specially for people who are fairly new to git), I suggest we stick to one set of recommendations for what to label the remotes. In [Contributing page](https://echopype.readthedocs.io/en/stable/contributing.html) (which I need to update!!), we refer to `origin` (one's fork) vs `upstream`, whereas here you use `fork` (one's fork) vs `origin`. I think I'd vote for upstream & origin, for now.

**Comment by lsetiawan** [comment]
> so no tests were run for these changes since the CI is not pointed to it, but seems like we're now in place to add that in...

@stuara  you can add this module into the `MODULE_TO_TEST` dictionary now within `run-test.py`:
https://github.com/OSOceanAcoustics/echopype/blob/d8d1a5799e6ff485a903e1bb6432c3096240551f/.ci_helpers/run-test.py#L25

```
"metrics": {}
```
Also, could you rename the `test_summary_statistics.py` to `test_metrics_summary_statistics.py`. Thanks!

**Comment by lsetiawan** [comment]
> In Contributing page (which I need to update!!), we refer to origin (one's fork) vs upstream, whereas here you use fork (one's fork) vs origin. I think I'd vote for upstream & origin, for now.

Thanks @emiliom! I am just used to referring origin as the original repo, but I do like the upstream/origin notion better, so one don't actually just push to origin if one has lots of power, which I have done time to time 😝 .

@stuara Please follow @emiliom, guidance for the git remote sources. Thanks!

**Comment by lsetiawan** [comment]
@stuara Looks like the test is now running, and you need to make some changes.

**Comment by stuara** [comment]
@leewujung all checks pass now

**Review by lsetiawan — APPROVED** [review]
LGTM

**Review by lsetiawan — CHANGES_REQUESTED** [review]
#416 has been merged. Please change the test file to be in a folder called `metrics` within `tests`. So the path should be `echopype/tests/metrics/test_metrics_summary_statistics.py`. Thanks! Also, please pull in the latest dev again.

**Review by lsetiawan — APPROVED** [review]
Thanks for making the updates @stuara 😄

**Comment by leewujung** [comment]
Closing this as latest are now in #444.

**Pull request closed without merging**
