### PR TITLE
Add function to correct ping_time reversal

### PR DESCRIPTION
**Pull request by leewujung**
This PR adds a function to detect and correct reversed `ping_time` sometimes observed in EK60. 

If no `ping_time` reversal is detected the original timestamps are returned.

If reversed `ping_time` exists, the function uses the median `ping_time` difference within a local window to infer and correct the timestamp.

@emiliom : could you try this on the hake survey file you've seen this problem before? Thanks!

### CODE REVIEW

**Comment by emiliom** [comment]
FYI, I'm finally in a position to test this. Hopefully today.

We'll have to change this PR regardless, b/c it was originally set for merging into `class-redesign`.

**Comment by leewujung** [comment]
Reopening this PR as I think I closed it accidentally.

**Comment by emiliom** [comment]
Following up on my own comments:

> FYI, I'm finally in a position to test this. Hopefully today.

I'm getting there!

> We'll have to change this PR regardless, b/c it was originally set for merging into class-redesign.

I see you've already done this -- thanks!

**Comment by leewujung** [comment]
I'll merge this so @imranmaj can use/change these for the EchoData combine function.

**Comment by emiliom** [comment]
>I'll merge this so @imranmaj can use/change these for the EchoData combine function.

Great. Is that work specific to ADCP, or the general combine functionality?

**Comment by leewujung** [comment]
This is for the general combine functionality :)

**Pull request merged**
