### PR TITLE
Skip unneeded datagrams

### PR DESCRIPTION
**Pull request by ngkavin**
When selecting certain datatypes to save such as the GPS information, all data in the raw files was parsed and the unneeded datagrams were ignored. This change peeks at the next datagram and parses it only if it is needed, which will save computation time in cases where the whole raw file does not need to be saved.

Also fixes a bug in the peek function from the parser.

### CODE REVIEW

**Comment by leewujung** [comment]
I'll review and comment on this after v0.5.0 is out, because 1) this feature is not already in place for v0.4.1, and 2) the operations, from the call through Convert to assembly of output files, needs to be verified with tests.

**Comment by emiliom** [comment]
ref: This PR is directly related to a subset of [this discussion](https://github.com/OSOceanAcoustics/echopype/discussions/225#discussioncomment-238638)

I, too, can review the PR after 0.5.0 is out.

**Comment by leewujung** [comment]
This PR probably needs to be closed because the code has gone through structural changes in v0.5.0, but we may want to consider reusing some of the changes here. Specifically the part about selecting which type of datagrams to read for EK echosounder data. I'll keep this PR open for now and let's discuss that in the next couple meetings.

**Comment by lsetiawan** [comment]
Stale PR. As Wu-Jung has noted. I put a label on it to easily find it again. Closing for now.

**Pull request closed without merging**
