### PR TITLE
Remove `preprocess` from subpackages to test in run-test [all tests ci]

### PR DESCRIPTION
**Pull request by emiliom**
See #1076.

### CODE REVIEW

**Comment by lsetiawan** [comment]
This is great! I'm glad it's pretty straightforward. I am wondering however, has this submodule been removed? The main CI do run all the tests using `pytest` directly rather than using the `run-test.py` script.

**Comment by emiliom** [comment]
The preprocess subpackage is not removed. All the preprocess tests were removed back when preprocess was deprecated.

`run-test.py` is still being used in `pr.yml`:
https://github.com/OSOceanAcoustics/echopype/blob/e11c665b8098d1badf213cb1a326afaa92d12f67/.github/workflows/pr.yaml#L89-L93

Am I missing something?

**Comment by emiliom** [comment]
BTW, I forgot to use "[all tests ci]" in the PR title, so it looks like most of the tests didn't run here. I added it after the fact  here, but it looks like a title edit doesn't spawn a re-run of tests.

**Comment by lsetiawan** [comment]
> BTW, I forgot to use "[all tests ci]" in the PR title, so it looks like most of the tests didn't run here. I added it after the fact here, but it looks like a title edit doesn't spawn a re-run of tests.

Yea, I haven't found a way to trigger actions when changing the title, but closing and opening seem to always, work and that's what I did. Seems like now the proper action step is running.

**Comment by emiliom** [comment]
> Yea, I haven't found a way to trigger actions when changing the title, but closing and opening seem to always, work and that's what I did. Seems like now the proper action step is running.

Oooh, great trick, thanks! I'll remember that.

**Review by lsetiawan — APPROVED** [review]

**Pull request merged**
