### PR TITLE
Refactor split-beam processing and add BB with pc option

### PR DESCRIPTION
**Pull request by leewujung**
## Overview

This PR completely refactors the split-beam processing code and addresses #890.

### Immediately related to split-beam processing
- consolidate complex sample split-beam processing to a single function `get_angle_complex_samples`, which:
   - handles both BB and CW cases
   - handles both with and without pulse compression cases
- fix bugs in determining whether to pass in all or single channels for split-beam processing based on `beam_type`

### Others
- add `angle_sensitivity_*` to `CAL_PARAMS`
- add BB freq_center re frequency_nominal scaling for `angle_sensitivity_*` and `beamwidth_*` in cal params construction
- move `get_filter_coeff()` and `get_vend_filter_EK80()` to `ek80_complex.py`
   - this allows using pulse compression in split-beam BB complex with pc option
- change compress_pulse to output xr.DataArray instead of xr.Dataset
- rename `test_consolidate.py` to `test_consolidate_integration.py`
- overhaul docstring

Note this built on top of #955 so need to pull in `dev` once that is merged.

### CODE REVIEW

**Comment by leewujung** [comment]
The actual changes (on top of what's ins #955) are captured in https://github.com/leewujung/echopype/pull/31.

**Review by lsetiawan — CHANGES_REQUESTED** [review]
Please see my review in https://github.com/leewujung/echopype/pull/31

**Review by lsetiawan — APPROVED** [review]
LGTM!

**Comment by leewujung** [comment]
Found a missing test case for EK80 CW power data. I am pretty sure the code works right now, but don't have Echoview dongle to produce a comparison dataset. Will get this PR merged and add this later.

**Pull request merged**
