### PR TITLE
Handle missing `receiver_sampling_frequency` in EK80 data [all tests ci]

### PR DESCRIPTION
**Pull request by praneethratna**
Addresses #1217 by adding a check for `receiver_sampling_frequency` not being equal to 0 or else setting it to its default value.

CC @leewujung

### CODE REVIEW

**Comment by leewujung** [comment]
@praneethratna : This looks great! I verified the file @icaro-00 and those that we already have in the test data, and confirmed that even if `receiver_sampling_frequency` exists it could be 0, which is a case we haven't seen previously. Before we have only seen files that do not contain this field altogether, from earlier versions of the EK80 software.

Please feel free to merge! Thanks!

**Review by leewujung — APPROVED** [review]

**Comment by leewujung** [comment]
BTW, @icaro-00 : Do you have a file that is much smaller that we could include in our test data set (e.g., a few MB)? We typically do not include large files because that lengthens the time of our test runs significantly. Thanks!

**Review by leewujung — APPROVED** [review]

**Comment by icaro-00** [comment]
> BTW, @icaro-00 : Do you have a file that is much smaller that we could include in our test data set (e.g., a few MB)? We typically do not include large files because that lengthens the time of our test runs significantly. Thanks!

Hi @leewujung, the smallest find I could find is 300MB. Here is the link: https://wetransfer.com/downloads/1e20766c3f67ddccda9cfbcecb20edec20231116101129/4d5f8f 

Is the errror fixed and available by updating Echopype? Or should I still wait for the 0.8.2 release to be completed 100 percent?

Thank you!

**Comment by icaro-00** [comment]
I actually managed to find another smaller file, 20MB.

Here the link: 
https://wetransfer.com/downloads/f54d5fd680e8d724926cd7849dfe782020231116120052/2d0d2b

**Comment by leewujung** [comment]
Thanks Vogt the files @icaro-00 !

You could try to pip install the dev branch that had the fix included, like shown [here].(https://www.w3docs.com/snippets/python/pip-install-from-git-repo-branch.html)

Our goal is to get v0.8.2 out on Nov 20, so you could also wait for that if it’s not too far away for you.

**Comment by leewujung** [comment]
@praneethratna : I added the 20MB file into the google folder: `ek80/D20230804-T083032.raw`. Please add a test for testing for the stored `receiver_sampling_frequency` value when you have a chance. Thank you!

**Comment by icaro-00** [comment]
> Thanks Vogt the files @icaro-00 !
> 
> You could try to pip install the dev branch that had the fix included, like shown [here](https://www.w3docs.com/snippets/python/pip-install-from-git-repo-branch.html)
> 
> Our goal is to get v0.8.2 out on Nov 20, so you could also wait for that if it’s not too far away for you.

Thank you for the info @leewujung, I will wait for Nov 20, and thanks for helping on this!

**Pull request merged**
