### PR TITLE
Add transient noise and impulsive noise masks

### PR DESCRIPTION
**Pull request by beatfactor**

### CODE REVIEW

**Comment by leewujung** [comment]
Hey @beatfactor : would you like to keep this open and discuss the code? :)

**Comment by beatfactor** [comment]
Sure, I can do that, but please bear in mind that we are restructuring the code in our own fork and the feature is not yet ready. Tests are also pending.

**Comment by leewujung** [comment]
@beatfactor : Do you want to discuss the restructuring so that your change could make its way into this repo when ready?

**Comment by beatfactor** [comment]
Yes, we have a few more PRs in the works (also related to denoising), and it would be nice if we could discuss those as well.

**Comment by leewujung** [comment]
@beatfactor : Sounds good. How about we shoot for some time in the week of Aug 21? I am away most of this coming week -- I'll shoot you an email to coordinate.

Skimming through the code, I think the main thing would be that some functions in your `mask_transformation.py` can be moved into different subpackages in echopype, like `commongrid`, and some can remain in `utils`. Some seem to address some open issues that we've not had time to implement (e.g. https://github.com/OSOceanAcoustics/echopype/issues/726, https://github.com/OSOceanAcoustics/echopype/issues/727, etc), which is great!

**Comment by simedroniraluca** [comment]
> @beatfactor : Sounds good. How about we shoot for some time in the week of Aug 21? I am away most of this coming week -- I'll shoot you an email to coordinate.
> 
> Skimming through the code, I think the main thing would be that some functions in your `mask_transformation.py` can be moved into different subpackages in echopype, like `commongrid`, and some can remain in `utils`. Some seem to address some open issues that we've not had time to implement (e.g. #726, #727, etc), which is great!

@leewujung  We’ve removed all functions taken from EchoPy that aren’t related to transient noise. Now, the mask transformation file only contains functions specific to transient noise.

**Comment by ruxandra-valcu** [comment]
Description: 

Porting the impulse noise and transient noise masking algorithms from Echopy:

https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_impulse.py
https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_transient.py

These include both methods published in Ryan et al - (2015) ‘Reducing bias due to noise and attenuation in open-ocean echo integration data’, ICES Journal of Marine Science, 72: 2482–2493 and as yet unpublished Fielding methods

**Comment by beatfactor** [comment]
Closing for now, we'll reopen once we sort out the commit history.

**Pull request closed without merging**
